"""PHASE 2, part one - turning the reconstruction into something a model can learn from.

THE TRAP THIS MODULE EXISTS TO AVOID, stated first because it would invalidate everything.

The obvious way to "train the model on how the players behaved" is to fit a policy to the
cohort flows the reconstruction produced. That is circular: those flows were generated by the
asserted rules in `cohorts.py`, so a model fitted to them learns my priors and nothing about
the market. It would score beautifully and mean nothing.

So the target here is never a cohort's behaviour. **The target is the market** - the forward
return of an asset, which the model cannot influence and the reconstruction never saw. The
cohort state enters as FEATURES. The question the training then asks is the design's V4, and
it is the only question worth asking of this architecture:

    does knowing who holds the coins and who holds the dry powder help predict what
    happens next, over and above what the price series already says?

TWO FEATURE GROUPS, KEPT APART ON PURPOSE

  MARKET   returns on four horizons, drawdown, realised volatility, perpetual funding.
           This is the baseline - roughly what systems 04 to 08 already mine.
  LEDGER   the cohort state: dry powder, who owns the float, how far each segment is from
           its cost basis, and how the segments' holdings changed over the last month.

They are returned separately so the training can fit MARKET alone and MARKET+LEDGER with
everything else held identical. A strict addition is the only honest way to ask whether the
expensive half earned its place.

EVERY FEATURE IS CAUSAL. A row dated `d` uses the ledger and the prices as they stood at the
close of `d`, and the label is the return from `d` to `d + HORIZON`. The ledger state at `d`
is itself built only from buckets up to `d`, so there is no path by which the label reaches
the features.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

import quantlab_catalog as cat

from . import segments as SEG

#: Days ahead the label looks. The architecture's claim is about slow stocks - who has run
#: out of money, who is underwater - so the horizon is a week rather than a bar.
HORIZON = 7

MARKET_NAMES = (
    "r1", "r7", "r30", "r90", "drawdown", "vol30", "funding",
    # --- T2, the cycle state. Every row above describes a day; these describe WHERE IN THE
    # CYCLE that day sits, which is the thing a model of participant behaviour most needs and
    # the thing this feature set most obviously lacked. The operator's phrasing: "la tendencia
    # que vayamos arrastrando".
    "dd_days",        # how LONG the drawdown has lasted, not just how deep. A 40% fall three
                      # weeks old and one two years old are different markets with the same
                      # depth, and only one of them has exhausted its sellers.
    "dist_ath",       # distance from the all-time high of the whole record, not a 1y window
    "vol_regime",     # 30-day volatility against its own 2-year percentile
    "trend_state",    # price against its 200-day average, in volatility units
    "greed",          # the crowd's own sentiment index, in the catalogue since system 06 and
                      # never once used by system 09
    "greed_d30",      # and whether it is turning
)
_SEG_FEATURES = (SEG.WHALES, SEG.RETAIL, SEG.INSTITUTIONAL, SEG.MARKET_MAKERS)
LEDGER_NAMES = (
    "dry_powder", "dry_powder_d30", "mcap_d30", "players_d30",
    *[f"share_{s}" for s in _SEG_FEATURES],
    *[f"float_{s}" for s in _SEG_FEATURES],
    *[f"flow30_{s}" for s in _SEG_FEATURES],
    *[f"basisgap_{s}" for s in _SEG_FEATURES],
    "basisgap_sector", "miner_float",
)


@dataclass
class Dataset:
    """A feature matrix with its index kept beside it, so a row can always be traced back."""
    days: list[str]
    symbols: list[str]
    market: np.ndarray          # (n, len(MARKET_NAMES))
    ledger: np.ndarray          # (n, len(LEDGER_NAMES))
    #: The world outside crypto - rates, liquidity, the dollar, risk appetite - aligned to
    #: PUBLICATION rather than to the observation date. Kept as its own block so the strict
    #: addition test can ask what it is worth, exactly as it does for the ledger.
    world: np.ndarray           # (n, len(world.NAMES))
    y: np.ndarray               # (n,) the LABEL: relative or absolute, see `build`
    price: np.ndarray           # (n,) the price the row was taken at
    #: The raw forward return, always, whatever `y` holds. Kept so a market-direction model
    #: can be trained on the level while the cross-sectional model trains on the relative.
    y_abs: np.ndarray = None    # type: ignore[assignment]
    #: The universe's own mean forward return that day - the market's move, which is exactly
    #: what the relative target removes.
    y_market: np.ndarray = None  # type: ignore[assignment]

    def __len__(self) -> int:
        return len(self.y)

    def mask(self, lo: str | None = None, hi: str | None = None) -> np.ndarray:
        """Rows whose DAY lies in [lo, hi). Era selection is always by date, never by index."""
        d = np.array(self.days)
        m = np.ones(len(d), dtype=bool)
        if lo:
            m &= d >= lo
        if hi:
            m &= d < hi
        return m


def _greed_daily() -> dict[str, float]:
    """The crowd's own fear-and-greed index, per day.

    It has been in the catalogue since system 06 and system 09 never read it, which is
    embarrassing for a system whose entire thesis is participant behaviour: this is the one
    published series that measures the crowd's state of mind directly rather than inferring
    it from a balance sheet.
    """
    try:
        rows = cat.feargreed()
    except (FileNotFoundError, AttributeError):
        return {}
    from datetime import datetime, timezone
    out = {}
    for r in rows:
        # The catalogue stores it as a unix timestamp, which is a UTC midnight.
        ts = r.get("t_s")
        day = (datetime.fromtimestamp(ts, timezone.utc).strftime("%Y-%m-%d") if ts
               else str(r.get("date") or r.get("day") or "")[:10])
        val = r.get("value")
        if day and val is not None:
            try:
                out[day] = float(val)
            except (TypeError, ValueError):
                continue
    return out


def _safe(x: float, default: float = 0.0) -> float:
    return x if isinstance(x, (int, float)) and math.isfinite(x) else default


def build(traj, funding: dict[str, list[dict]] | None = None,
          horizon: int = HORIZON, target: str = "relative") -> Dataset:
    """One row per (symbol, day) that has enough history behind it and a label ahead of it.

    `target` decides what the model is asked to learn, and it is the most consequential
    argument in this package:

      "absolute"  the raw forward return. What v1 used, and the reason the model forecast a
                  rise on 250 days out of 250: across 2017-2025 the mean 30-day return is
                  large and positive, so a model with weak features minimises its loss by
                  predicting the era's drift and ignoring its inputs. Every information
                  coefficient measured on this target is contaminated by that drift.
      "relative"  the forward return MINUS the universe's mean forward return that day. The
                  drift cancels exactly, a constant forecast scores zero, and the only way to
                  do well is to know which asset beats which - the one question the evidence
                  says this model can answer.

    Both are always available afterwards as `y_abs` and `y_market`; `y` is whichever was asked
    for, so no consumer can accidentally mix them.
    """
    days = traj.days
    n_days = len(days)
    idx = {d: i for i, d in enumerate(days)}
    fund = _funding_daily(funding or {})
    greed = _greed_daily()

    # Price path per symbol, forward-filled across days the symbol did not print.
    symbols = sorted({s for p in traj.prices for s in p})
    px: dict[str, list[float]] = {}
    for s in symbols:
        seq, last = [], 0.0
        for p in traj.prices:
            last = p.get(s, last)
            seq.append(last)
        px[s] = seq

    rows_day, rows_sym, mkt, led, ys, prices = [], [], [], [], [], []
    for s in symbols:
        p = px[s]
        first = next((i for i, v in enumerate(p) if v > 0), None)
        if first is None:
            continue
        for i in range(first + 91, n_days - horizon):
            if p[i] <= 0 or p[i + horizon] <= 0:
                continue
            seg = traj.segments[i]
            total_assets = sum(v["assets"] for v in seg.values())
            total_cash = sum(v["cash"] for v in seg.values())
            wealth = total_assets + total_cash
            if wealth <= 0:
                continue
            units = {k: seg[k]["coins"].get(s, 0.0) for k in SEG.ORDER}
            float_s = sum(units.values())
            if float_s <= 0:
                continue

            j = max(0, i - 30)
            seg30 = traj.segments[j]
            prev_assets = sum(v["assets"] for v in seg30.values())
            prev_cash = sum(v["cash"] for v in seg30.values())
            prev_wealth = prev_assets + prev_cash

            ret = lambda k: (p[i] / p[i - k] - 1.0) if p[i - k] > 0 else 0.0   # noqa: E731
            window = [p[k] / p[k - 1] - 1.0 for k in range(i - 29, i + 1) if p[k - 1] > 0]
            peak = max(p[max(0, i - 365):i + 1]) or p[i]
            vol30 = float(np.std(window)) if len(window) > 5 else 0.0

            # --- T2, the cycle state -------------------------------------------------
            ath = max(p[first:i + 1]) or p[i]
            dd_days = 0
            k = i
            while k > first and p[k] < ath:          # how long since the record high
                dd_days += 1
                k -= 1
            hist = [float(np.std([p[t] / p[t - 1] - 1.0
                                  for t in range(m - 29, m + 1) if p[t - 1] > 0]))
                    for m in range(max(first + 30, i - 504), i + 1, 21)]
            vol_regime = (sum(1 for v in hist if v <= vol30) / len(hist)) if hist else 0.5
            ma200 = float(np.mean(p[max(first, i - 199):i + 1]))
            trend = ((p[i] / ma200 - 1.0) / vol30) if (ma200 > 0 and vol30 > 1e-9) else 0.0
            g = greed.get(days[i])
            g30 = greed.get(days[max(0, i - 30)])

            mkt.append([
                _safe(ret(1)), _safe(ret(7)), _safe(ret(30)), _safe(ret(90)),
                _safe(p[i] / peak - 1.0),
                _safe(vol30),
                _safe(fund.get(s, {}).get(days[i], 0.0)),
                _safe(min(dd_days, 900) / 900.0),
                _safe(p[i] / ath - 1.0),
                _safe(vol_regime, 0.5),
                _safe(max(-5.0, min(5.0, trend))),
                _safe((g if g is not None else 50.0) / 100.0, 0.5),
                _safe(((g - g30) / 100.0) if (g is not None and g30 is not None) else 0.0),
            ])

            feats = [
                _safe(total_cash / wealth),
                _safe(total_cash / wealth - (prev_cash / prev_wealth if prev_wealth else 0.0)),
                _safe(traj.market_cap[i] / traj.market_cap[j] - 1.0
                      if traj.market_cap[j] > 0 else 0.0),
                _safe(traj.headcount[i] / traj.headcount[j] - 1.0
                      if traj.headcount[j] > 0 else 0.0),
            ]
            feats += [_safe(seg[k]["assets"] / total_assets if total_assets else 0.0)
                      for k in _SEG_FEATURES]
            feats += [_safe(units[k] / float_s) for k in _SEG_FEATURES]
            feats += [_safe((units[k] - seg30[k]["coins"].get(s, 0.0)) / float_s)
                      for k in _SEG_FEATURES]
            # How far each segment is from what it paid: above zero it is in profit and free
            # to sell, below zero it is underwater and either frozen or forced.
            for k in _SEG_FEATURES:
                q, b = units[k], seg[k]["basis"].get(s, 0.0)
                feats.append(_safe(p[i] / (b / q) - 1.0 if q > 1e-12 and b > 0 else 0.0))
            sec_b = sum(seg[k]["basis"].get(s, 0.0) for k in SEG.ORDER)
            feats.append(_safe(p[i] / (sec_b / float_s) - 1.0 if sec_b > 0 else 0.0))
            feats.append(_safe(units[SEG.MINERS] / float_s))
            led.append(feats)

            ys.append(p[i + horizon] / p[i] - 1.0)          # absolute, always
            prices.append(p[i])
            rows_day.append(days[i])
            rows_sym.append(s)

    # --- T1: turn the absolute label into a relative one ---------------------------
    # The market's move on each day is the mean forward return of everything trading that
    # day. Subtracting it is what makes a constant forecast worthless, which is the whole
    # point: the drift was doing the model's work for it and calling the result a signal.
    ys_abs = np.asarray(ys, dtype=np.float32)
    by_day: dict[str, list[int]] = {}
    for k, d in enumerate(rows_day):
        by_day.setdefault(d, []).append(k)
    y_market = np.zeros(len(ys_abs), dtype=np.float32)
    for d, ks in by_day.items():
        m = float(np.mean(ys_abs[ks]))
        for k in ks:
            y_market[k] = m
    y_used = (ys_abs - y_market) if target == "relative" else ys_abs

    from system009_participant_ledger import world as W
    return Dataset(days=rows_day, symbols=rows_sym,
                   market=np.asarray(mkt, dtype=np.float32),
                   ledger=np.asarray(led, dtype=np.float32),
                   world=W.block(rows_day),
                   y=y_used, y_abs=ys_abs, y_market=y_market,
                   price=np.asarray(prices, dtype=np.float32))


def _funding_daily(funding: dict[str, list[dict]]) -> dict[str, dict[str, float]]:
    from datetime import datetime, timezone
    out: dict[str, dict[str, float]] = {}
    for sym, rows in funding.items():
        acc: dict[str, list[float]] = {}
        for r in rows:
            d = datetime.fromtimestamp(int(r["t_ms"]) / 1000, timezone.utc).strftime("%Y-%m-%d")
            acc.setdefault(d, []).append(float(r["rate"]))
        out[sym] = {d: sum(v) / len(v) for d, v in acc.items()}
    return out
