"""PHASE 2, part one - turning the reconstruction into something a model can learn from.

THE TRAP THIS MODULE EXISTS TO AVOID, stated first because it would invalidate everything.

The obvious way to "train the model on how the players behaved" is to fit a policy to the
cohort flows the reconstruction produced. That is circular: those flows were generated by the
asserted rules in `cohorts.py`, so a model fitted to them learns my priors and nothing about
the market. It would score beautifully and mean nothing.

So the target here is never a cohort's behaviour. **The target is the market** - the forward
return of an asset, which the model cannot influence and the reconstruction never saw. The
cohort state enters as FEATURES. The question the training then asks is the design's V4, and
it is the only question worth asking of this architecture:

    does knowing who holds the coins and who holds the dry powder help predict what
    happens next, over and above what the price series already says?

TWO FEATURE GROUPS, KEPT APART ON PURPOSE

  MARKET   returns on four horizons, drawdown, realised volatility, perpetual funding.
           This is the baseline - roughly what systems 04 to 08 already mine.
  LEDGER   the cohort state: dry powder, who owns the float, how far each segment is from
           its cost basis, and how the segments' holdings changed over the last month.

They are returned separately so the training can fit MARKET alone and MARKET+LEDGER with
everything else held identical. A strict addition is the only honest way to ask whether the
expensive half earned its place.

EVERY FEATURE IS CAUSAL. A row dated `d` uses the ledger and the prices as they stood at the
close of `d`, and the label is the return from `d` to `d + HORIZON`. The ledger state at `d`
is itself built only from buckets up to `d`, so there is no path by which the label reaches
the features.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

from . import segments as SEG

#: Days ahead the label looks. The architecture's claim is about slow stocks - who has run
#: out of money, who is underwater - so the horizon is a week rather than a bar.
HORIZON = 7

MARKET_NAMES = ("r1", "r7", "r30", "r90", "drawdown", "vol30", "funding")
_SEG_FEATURES = (SEG.WHALES, SEG.RETAIL, SEG.INSTITUTIONAL, SEG.MARKET_MAKERS)
LEDGER_NAMES = (
    "dry_powder", "dry_powder_d30", "mcap_d30", "players_d30",
    *[f"share_{s}" for s in _SEG_FEATURES],
    *[f"float_{s}" for s in _SEG_FEATURES],
    *[f"flow30_{s}" for s in _SEG_FEATURES],
    *[f"basisgap_{s}" for s in _SEG_FEATURES],
    "basisgap_sector", "miner_float",
)


@dataclass
class Dataset:
    """A feature matrix with its index kept beside it, so a row can always be traced back."""
    days: list[str]
    symbols: list[str]
    market: np.ndarray          # (n, len(MARKET_NAMES))
    ledger: np.ndarray          # (n, len(LEDGER_NAMES))
    y: np.ndarray               # (n,) forward return over HORIZON days
    price: np.ndarray           # (n,) the price the row was taken at

    def __len__(self) -> int:
        return len(self.y)

    def mask(self, lo: str | None = None, hi: str | None = None) -> np.ndarray:
        """Rows whose DAY lies in [lo, hi). Era selection is always by date, never by index."""
        d = np.array(self.days)
        m = np.ones(len(d), dtype=bool)
        if lo:
            m &= d >= lo
        if hi:
            m &= d < hi
        return m


def _safe(x: float, default: float = 0.0) -> float:
    return x if isinstance(x, (int, float)) and math.isfinite(x) else default


def build(traj, funding: dict[str, list[dict]] | None = None,
          horizon: int = HORIZON) -> Dataset:
    """One row per (symbol, day) that has enough history behind it and a label ahead of it."""
    days = traj.days
    n_days = len(days)
    idx = {d: i for i, d in enumerate(days)}
    fund = _funding_daily(funding or {})

    # Price path per symbol, forward-filled across days the symbol did not print.
    symbols = sorted({s for p in traj.prices for s in p})
    px: dict[str, list[float]] = {}
    for s in symbols:
        seq, last = [], 0.0
        for p in traj.prices:
            last = p.get(s, last)
            seq.append(last)
        px[s] = seq

    rows_day, rows_sym, mkt, led, ys, prices = [], [], [], [], [], []
    for s in symbols:
        p = px[s]
        first = next((i for i, v in enumerate(p) if v > 0), None)
        if first is None:
            continue
        for i in range(first + 91, n_days - horizon):
            if p[i] <= 0 or p[i + horizon] <= 0:
                continue
            seg = traj.segments[i]
            total_assets = sum(v["assets"] for v in seg.values())
            total_cash = sum(v["cash"] for v in seg.values())
            wealth = total_assets + total_cash
            if wealth <= 0:
                continue
            units = {k: seg[k]["coins"].get(s, 0.0) for k in SEG.ORDER}
            float_s = sum(units.values())
            if float_s <= 0:
                continue

            j = max(0, i - 30)
            seg30 = traj.segments[j]
            prev_assets = sum(v["assets"] for v in seg30.values())
            prev_cash = sum(v["cash"] for v in seg30.values())
            prev_wealth = prev_assets + prev_cash

            ret = lambda k: (p[i] / p[i - k] - 1.0) if p[i - k] > 0 else 0.0   # noqa: E731
            window = [p[k] / p[k - 1] - 1.0 for k in range(i - 29, i + 1) if p[k - 1] > 0]
            peak = max(p[max(0, i - 365):i + 1]) or p[i]

            mkt.append([
                _safe(ret(1)), _safe(ret(7)), _safe(ret(30)), _safe(ret(90)),
                _safe(p[i] / peak - 1.0),
                _safe(float(np.std(window)) if len(window) > 5 else 0.0),
                _safe(fund.get(s, {}).get(days[i], 0.0)),
            ])

            feats = [
                _safe(total_cash / wealth),
                _safe(total_cash / wealth - (prev_cash / prev_wealth if prev_wealth else 0.0)),
                _safe(traj.market_cap[i] / traj.market_cap[j] - 1.0
                      if traj.market_cap[j] > 0 else 0.0),
                _safe(traj.headcount[i] / traj.headcount[j] - 1.0
                      if traj.headcount[j] > 0 else 0.0),
            ]
            feats += [_safe(seg[k]["assets"] / total_assets if total_assets else 0.0)
                      for k in _SEG_FEATURES]
            feats += [_safe(units[k] / float_s) for k in _SEG_FEATURES]
            feats += [_safe((units[k] - seg30[k]["coins"].get(s, 0.0)) / float_s)
                      for k in _SEG_FEATURES]
            # How far each segment is from what it paid: above zero it is in profit and free
            # to sell, below zero it is underwater and either frozen or forced.
            for k in _SEG_FEATURES:
                q, b = units[k], seg[k]["basis"].get(s, 0.0)
                feats.append(_safe(p[i] / (b / q) - 1.0 if q > 1e-12 and b > 0 else 0.0))
            sec_b = sum(seg[k]["basis"].get(s, 0.0) for k in SEG.ORDER)
            feats.append(_safe(p[i] / (sec_b / float_s) - 1.0 if sec_b > 0 else 0.0))
            feats.append(_safe(units[SEG.MINERS] / float_s))
            led.append(feats)

            ys.append(p[i + horizon] / p[i] - 1.0)
            prices.append(p[i])
            rows_day.append(days[i])
            rows_sym.append(s)

    return Dataset(days=rows_day, symbols=rows_sym,
                   market=np.asarray(mkt, dtype=np.float32),
                   ledger=np.asarray(led, dtype=np.float32),
                   y=np.asarray(ys, dtype=np.float32),
                   price=np.asarray(prices, dtype=np.float32))


def _funding_daily(funding: dict[str, list[dict]]) -> dict[str, dict[str, float]]:
    from datetime import datetime, timezone
    out: dict[str, dict[str, float]] = {}
    for sym, rows in funding.items():
        acc: dict[str, list[float]] = {}
        for r in rows:
            d = datetime.fromtimestamp(int(r["t_ms"]) / 1000, timezone.utc).strftime("%Y-%m-%d")
            acc.setdefault(d, []).append(float(r["rate"]))
        out[sym] = {d: sum(v) / len(v) for d, v in acc.items()}
    return out
